# vim: set ts=2 sw=2 ai si et:
---

image: debian:unstable

variables:
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths: []

before_script:
  - apt-get update -yq
  - apt-get dist-upgrade -yq
  - apt-get install -yq --install-recommends ansible-lint git

stages:
  - test

test:lint:
  stage: test
  script:
    - ansible-lint
